# Generated by Django 3.0.3 on 2020-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revendedor',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='revendedor',
            name='nome_completo',
            field=models.CharField(default='', max_length=60),
        ),
    ]
