# Generated by Django 3.0.3 on 2020-02-19 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200219_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='cpf',
            field=models.CharField(default='', max_length=14, validators=[django.core.validators.RegexValidator(code='nomatch', message='Como minimo 11 digitos', regex='^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$')]),
        ),
    ]
