# Generated by Django 3.0.3 on 2020-02-19 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200219_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='cpf',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message='Escreva so os 11 digitos', regex='^\\d{11}$')]),
        ),
    ]
