# Generated by Django 3.0.3 on 2020-02-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_revendedor_alt_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revendedor',
            name='nome_completo',
        ),
    ]
