# Generated by Django 3.0.3 on 2020-02-21 14:11

import cpffield.cpffield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_revendedor_nome_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revendedor',
            name='alt_cpf',
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='cpf',
            field=cpffield.cpffield.CPFField(default='', max_length=14, verbose_name='CPF'),
        ),
    ]
