# Generated by Django 3.0.3 on 2020-02-21 17:47

import cpffield.cpffield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20200221_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='cpf',
            field=cpffield.cpffield.CPFField(default='', max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
