# Generated by Django 3.0.3 on 2020-02-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20200221_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),
    ]
