# Generated by Django 3.0.3 on 2020-02-21 18:53

import cpffield.cpffield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20200221_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='cpf',
            field=cpffield.cpffield.CPFField(default='', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='username'),
        ),
    ]
