# Generated by Django 3.0.3 on 2020-02-20 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('valor', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('cpf', models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message='Escreva so os 11 digitos', regex='^\\d{11}$')])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('E', 'Em avaliação'), ('A', 'Aprovado')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
