# Generated by Django 3.0.3 on 2020-02-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20200220_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cpf',
        ),
    ]
