# Generated by Django 3.0.3 on 2020-02-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20200221_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
